WebBanHangn/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Diagnostics;
using WebBanHangn.Models;
using WebBanHangn.Repositories;

namespace WebBanHangn.Controllers
{
    public class HomeController : Controller
    {
        

        private readonly IProductRepository _productRepository;
        private readonly ICategoryRepository _categoryRepository;
        public HomeController(IProductRepository productRepository, ICategoryRepository categoryRepository)
        {
            _productRepository = productRepository;
            _categoryRepository = categoryRepository;
        }

        // Hiển thị danh sách sản phẩm
        public async Task<IActionResult> Index()
        {
            var products = await _productRepository.GetAllAsync();
            return View(products);
        }

        // Hiển thị form thêm sản phẩm mới
        public async Task<IActionResult> Add()
        {
            var categories = await _categoryRepository.GetAllAsync();
            ViewBag.Categories = new SelectList(categories, "Id", "Name");
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
        public async Task<IActionResult> Display(int id)
        {
            var product = await _productRepository.GetByIdAsync(id);
            if (product == null)
            {
                return NotFound();
            }
            return View(product);
        }
    }
}

WebBanHangn/Controllers/ShoppingCartController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using WebBanHangn.DataAccess;
using WebBanHangn.Extensions;
using WebBanHangn.Models;
using WebBanHangn.Repositories;

namespace WebBanHangn.Controllers
{
    [Authorize]
    public class ShoppingCartController : Controller
    {
        private readonly IProductRepository _productRepository;
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        public ShoppingCartController(ApplicationDbContext context, UserManager<ApplicationUser> userManager, IProductRepository productRepository)
        {
            _productRepository = productRepository;
            _context = context;
            _userManager = userManager;
        }
        public IActionResult Checkout()
        {
            return View(new Order());
        }
        [HttpPost]
        public async Task<IActionResult> Checkout(Order order)
        {
            var cart = HttpContext.Session.GetObjectFromJson<ShoppingCart>("Cart");
            if (cart == null || !cart.Items.Any())
            {
                // Xử lý giỏ hàng trống...
                return RedirectToAction("Index");
            }
            var user = await _userManager.GetUserAsync(User);
            order.UserId = user.Id;
            order.OrderDate = DateTime.UtcNow;
            order.TotalPrice = cart.Items.Sum(i => i.Price * i.Quantity);
            order.OrderDetails = cart.Items.Select(i => new OrderDetail
            {
                ProductId = i.ProductId,
                Quantity = i.Quantity,
                Price = i.Price
            }).ToList();
            _context.Orders.Add(order);
            await _context.SaveChangesAsync();
            HttpContext.Session.Remove("Cart");
            return View("OrderCompleted", order.Id); // Trang xác nhận hoàn thành đơn hàng
        }
        public async Task<IActionResult> AddToCart(int productId, int quantity)
        {
            // Giả sử bạn có phương thức lấy thông tin sản phẩm từ productId
            var product = await GetProductFromDatabase(productId);
            var cartItem = new CartItem
            {
                ProductId = productId,
                Name = product.Name,
                Price = product.Price,
                Quantity = quantity
            };
            var cart =
            HttpContext.Session.GetObjectFromJson<ShoppingCart>("Cart") ?? new
            ShoppingCart();
            cart.AddItem(cartItem);
            HttpContext.Session.SetObjectAsJson("Cart", cart);
            return RedirectToAction("Index");
        }
        public IActionResult Index()
        {
            var cart =
            HttpContext.Session.GetObjectFromJson<ShoppingCart>("Cart") ?? new
            ShoppingCart();
            return View(cart);
        }
        // Các actions khác...
        private async Task<Product> GetProductFromDatabase(int productId)
        {
            // Truy vấn cơ sở dữ liệu để lấy thông tin sản phẩm
            var product = await _productRepository.GetByIdAsync(productId);
            return product;
        }
        public IActionResult RemoveFromCart(int productId)
        {
            var cart =
            HttpContext.Session.GetObjectFromJson<ShoppingCart>("Cart");
            if (cart is not null)
            {
                cart.RemoveItem(productId);
                // Lưu lại giỏ hàng vào Session sau khi đã xóa mục
                HttpContext.Session.SetObjectAsJson("Cart", cart);
            }
            return RedirectToAction("Index");

        }
    }
}

WebBanHangn/Views/Home/Display.cshtml
@model WebBanHangn.Models.Product

<h2>@Model.Name</h2>

<div class="container mt-4">
    <div class="row">
        <!-- Danh sách sản phẩm -->
        <div class="col-md-9">
            <!-- Hiển thị sản phẩm bằng dạng dòng sản phẩm sử dụng Bootstrap Row và Col -->
            <div class="row">
                <!-- Sản phẩm -->
                <div class="col">
                    <div class="card">
                        <img src="@Model.ImageUrl" class="card-img-top" alt="...">
                        <div class="card-body">
                            <p class="card-text">@Model.Description</p>
                            <p class="card-text">@Model.Price</p>
                        </div>
                        
                    </div>
                </div>
            </div>

        </div>
        <!-- Sidebar -->
        <div class="col-md-3">
            <div class="bg-primary text-white p-3">
                <h5>Social Media</h5>
                <ul class="list-unstyled">
                    <li><a class="text-white" href="#">Facebook</a></li>
                    <li><a class="text-white" href="#">Twitter</a></li>
                    <li><a class="text-white" href="#">Instagram</a></li>
                    <li><a class="text-white" href="#">LinkedIn</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>


<a asp-action="Index" class="btn btn-info">Back to List</a>

WebBanHangn/Views/Home/Index.cshtml
@model IEnumerable<WebBanHangn.Models.Product>

@{
    ViewData["Title"] = "Home Page";
    int numOfQuantity = 1;
}

<div class="container mt-4 py-2">
    <div class="row">
        <!-- Danh sách sản phẩm -->
        <div class="col-md-9">
            <!-- Hiển thị sản phẩm bằng dạng dòng sản phẩm sử dụng Bootstrap Row và Col -->
            <div class="row row-cols-1 row-cols-md-3 g-4">

                @foreach (var product in Model)
                {
                    <!-- Sản phẩm -->
                    <div class="col">
                        <div class="card">
                            <img src="@product.ImageUrl" class="card-img-top" alt="..." style="max-height:150px;">
                            <div class="card-body">
                                <h5 class="card-title">Name: <strong>@product.Name</strong></h5>
                                
                                <p class="card-text">Price: <strong>@product.Price.ToString("#,##0") Vnđ</strong></p>
                                <p class="card-text">Cate: <strong>@(product.Category?.Name ?? "No Category")</strong></p>

                                <a asp-action="Display" asp-route-id="@product.Id" class="btn btn-warning">View</a>                                |
                                <a asp-controller="ShoppingCart" asp-action="AddToCart" asp-route-productId="@product.Id" asp-route-quantity="@numOfQuantity">
                                    <button class="btn btn-primary">

                                        <i class="bi-cart-fill me-1"></i> Add to Cart
                                    </button>
                                </a>
                            </div>
                        </div>
                    </div>
                }
            </div>

        </div>
        
    </div>
</div>