WebBanHangn/Models/Product.cs
using System.ComponentModel.DataAnnotations;

namespace WebBanHangn.Models
{
    public class Product
    {
        public int Id { get; set; }
        [Required, StringLength(100)]
        public string Name { get; set; }
        [Range(0.01, 10000.00)]
        public decimal Price { get; set; }
        public string Description { get; set; }
        public string? ImageUrl { get; set; }
        public List<ProductImage>? Images { get; set; }
        public int CategoryId { get; set; }
        public Category? Category { get; set; }

    }
}

WebBanHangn/Areas/Admin/Controllers/ProductController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using WebBanHangn.Models;
using WebBanHangn.Repositories;

namespace WebBanHangn.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class ProductController : Controller
    {
        private readonly IProductRepository _productRepository;
        private readonly ICategoryRepository _categoryRepository;
        public ProductController(IProductRepository productRepository, ICategoryRepository categoryRepository)
        {
            _productRepository = productRepository;
            _categoryRepository = categoryRepository;
        }

        // Hiển thị danh sách sản phẩm
        public async Task<IActionResult> Index()
        {
            var products = await _productRepository.GetAllAsync();
            return View(products);
        }

        // Hiển thị form thêm sản phẩm mới
        public async Task<IActionResult> Add()
        {
            var categories = await _categoryRepository.GetAllAsync();
            ViewBag.Categories = new SelectList(categories, "Id", "Name");
            return View();
        }
        // Xử lý thêm sản phẩm mới
        [HttpPost]
        public async Task<IActionResult> Add(Product product, IFormFile

        imageUrl)
        {
            if (ModelState.IsValid)
            {
                if (imageUrl != null)
                {
                    // Lưu hình ảnh đại diện tham khảo bài 02 hàm SaveImage
                    product.ImageUrl = await SaveImage(imageUrl);
                }
                await _productRepository.AddAsync(product);
                return RedirectToAction(nameof(Index));
            }
            // Nếu ModelState không hợp lệ, hiển thị form với dữ liệu đã nhập
            var categories = await _categoryRepository.GetAllAsync();
            ViewBag.Categories = new SelectList(categories, "Id", "Name");
            return View(product);
        }

        // Viết thêm hàm SaveImage (tham khảo bài 02)
        private async Task<string> SaveImage(IFormFile image)
        {
            var savePath = Path.Combine("wwwroot/images", image.FileName); //Thay đổi đường dẫn theo cấu hình của bạn

            using (var fileStream = new FileStream(savePath, FileMode.Create))
            {
                await image.CopyToAsync(fileStream);
            }
            return "/images/" + image.FileName; // Trả về đường dẫn tương đối
        }

        // Hiển thị thông tin chi tiết sản phẩm
        public async Task<IActionResult> Display(int id)
        {
            var product = await _productRepository.GetByIdAsync(id);
            if (product == null)
            {
                return NotFound();
            }
            return View(product);
        }
        // Hiển thị form cập nhật sản phẩm
        public async Task<IActionResult> Update(int id)
        {
            var product = await _productRepository.GetByIdAsync(id);
            if (product == null)
            {
                return NotFound();
            }
            var categories = await _categoryRepository.GetAllAsync();
            ViewBag.Categories = new SelectList(categories, "Id", "Name",

            product.CategoryId);

            return View(product);
        }

        // Xử lý cập nhật sản phẩm
        [HttpPost]
        public async Task<IActionResult> Update(int id, Product product, IFormFile imageUrl)
        {
            ModelState.Remove("ImageUrl"); // Loại bỏ xác thực ModelState cho ImageUrl
            if (id != product.Id)
            {
                return NotFound();
            }


            if (ModelState.IsValid)
            {


                var existingProduct = await _productRepository.GetByIdAsync(id); // Giả định có phương thức GetByIdAsync


                // Giữ nguyên thông tin hình ảnh nếu không có hình mới được tải lên
                if (imageUrl == null)
                {
                    product.ImageUrl = existingProduct.ImageUrl;
                }
                else
                {
                    // Lưu hình ảnh mới
                    product.ImageUrl = await SaveImage(imageUrl);
                }
                // Cập nhật các thông tin khác của sản phẩm
                existingProduct.Name = product.Name;
                existingProduct.Price = product.Price;
                existingProduct.Description = product.Description;
                existingProduct.CategoryId = product.CategoryId;
                existingProduct.ImageUrl = product.ImageUrl;


                await _productRepository.UpdateAsync(existingProduct);

                return RedirectToAction(nameof(Index));
            }
            var categories = await _categoryRepository.GetAllAsync();
            ViewBag.Categories = new SelectList(categories, "Id", "Name");
            return View(product);
        }

        // Hiển thị form xác nhận xóa sản phẩm
        public async Task<IActionResult> Delete(int id)
        {
            var product = await _productRepository.GetByIdAsync(id);
            if (product == null)
            {
                return NotFound();
            }
            return View(product);
        }

        // Xử lý xóa sản phẩm
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _productRepository.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

WebBanHangn/Areas/Admin/Views/Product/Add.cshtml
@model WebBanHangn.Models.Product
@using Microsoft.AspNetCore.Mvc.Rendering
@{
    ViewData["Title"] = "Add";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Add Product</h2>

<form asp-action="Add" method="post" enctype="multipart/form-data">
    <div class="form-group">
        <label asp-for="Name"></label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Price"></label>
        <input asp-for="Price" class="form-control" />
        <span asp-validation-for="Price" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Description"></label>
        <textarea asp-for="Description" class="form-control"></textarea>
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="CategoryId">Category</label>
        <select asp-for="CategoryId" asp-items="ViewBag.Categories" class="form-control"></select>
    </div>
    <div class="form-group">
        <label asp-for="ImageUrl">Product Image</label>
        <input type="file" asp-for="ImageUrl" class="form-control" />
    </div>
    <button type="submit" class="btn btn-primary mt-3 px-3">Add</button>
</form>

WebBanHangn/Areas/Admin/Views/Product/Delete.cshtml
@model WebBanHangn.Models.Product

<h2>Delete Product</h2>

<form asp-action="Delete" method="post">
    <input type="hidden" asp-for="Id" />
    <p>Are you sure you want to delete @Model.Name?</p>
    <button type="submit" class="btn btn-danger">Delete</button>
</form>

<a asp-action="Index" class="btn btn-success mt-4">Back to List</a>

WebBanHangn/Areas/Admin/Views/Product/Display.cshtml
@model WebBanHangn.Models.Product

<h2>@Model.Name</h2>

<div class="container mt-4">
    <div class="row">
        <!-- Danh sách sản phẩm -->
        <div class="col-md-9">
            <!-- Hiển thị sản phẩm bằng dạng dòng sản phẩm sử dụng Bootstrap Row và Col -->
            <div class="row">
                <!-- Sản phẩm -->
                <div class="col">
                    <div class="card">
                        <img src="@Model.ImageUrl" class="card-img-top" alt="...">
                        <div class="card-body">
                            <p class="card-text">@Model.Description</p>
                            <p class="card-text">@Model.Price</p>
                        </div>

                    </div>
                </div>
            </div>

        </div>
        <!-- Sidebar -->
        <div class="col-md-3">
            <div class="bg-primary text-white p-3">
                <h5>Social Media</h5>
                <ul class="list-unstyled">
                    <li><a class="text-white" href="#">Facebook</a></li>
                    <li><a class="text-white" href="#">Twitter</a></li>
                    <li><a class="text-white" href="#">Instagram</a></li>
                    <li><a class="text-white" href="#">LinkedIn</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>


<a asp-action="Index" class="btn btn-info">Back to List</a>

WebBanHangn/Areas/Admin/Views/Product/Index.cshtml
@model IEnumerable<WebBanHangn.Models.Product>

<h2>Products</h2>


<div class="container mt-4">
    <div class="row">
        <!-- Danh sách sản phẩm -->
        <div class="col-md-9">
            <!-- Hiển thị sản phẩm bằng dạng dòng sản phẩm sử dụng Bootstrap Row và Col -->
            <div class="row row-cols-1 row-cols-md-3 g-4">


                @foreach (var product in Model)
                {
                    <!-- Sản phẩm -->
                    <div class="col">
                        <div class="card">
                            <img src="@product.ImageUrl" class="card-img-top" alt="..." style="max-height:135px;">
                            <div class="card-body">
                                <h5 class="card-title">Name: <strong>@product.Name</strong></h5>
                                <p class="card-text">Des: <strong>@product.Description</strong></p>
                                <p class="card-text">Price: <strong>@product.Price</strong></p>
                                <p class="card-text">Cate: <strong>@(product.Category?.Name ?? "No Category")</strong></p>

                                @* <a asp-action="Display" href="/Admin/Product/@product.Id" class="btn btn-warning">View</a> *@
                                @* <a href="@Url.Action("Display", "Admin", new { id = product.Id })" class="btn btn-warning">View</a>|
                                <a href="@Url.Action("Update", "Admin", new { id = product.Id })" class="btn btn-warning">Edit</a>|
                                <a href="@Url.Action("Delete", "Admin", new { id = product.Id })" class="btn btn-warning">Delete</a>| *@
                                <a href="/Admin/Product/Display/@(product.Id)" class="btn btn-warning">View</a>
                                <a href="/Admin/Product/Update/@(product.Id)" class="btn btn-success">Update</a>
                                <a href="/Admin/Product/Delete/@(product.Id)" class="btn btn-dark">Delete</a>
                            </div>
                        </div>
                    </div>
                }
            </div>

        </div>
        <!-- Sidebar -->
        <div class="col-md-3">
            <div class="bg-primary text-white p-3">
                <h5>Social Media</h5>
                <ul class="list-unstyled">
                    <li><a class="text-white" href="#">Facebook</a></li>
                    <li><a class="text-white" href="#">Twitter</a></li>
                    <li><a class="text-white" href="#">Instagram</a></li>
                    <li><a class="text-white" href="#">LinkedIn</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>

WebBanHangn/Areas/Admin/Views/Product/Update.cshtml
@model WebBanHangn.Models.Product
@using Microsoft.AspNetCore.Mvc.Rendering
@{
    ViewData["Title"] = "Edit Product";
}

<h2>Edit Product</h2>

<form asp-action="Update" method="post" asp-area="Admin" enctype="multipart/form-data" asp-controller="Product" asp-route-id="@Model.Id" >
    <input type="hidden" asp-for="Id" />
    <div class="form-group">
        <label asp-for="Name"></label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Price"></label>
        <input asp-for="Price" class="form-control" />
        <span asp-validation-for="Price" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Description"></label>
        <textarea asp-for="Description" class="form-control"></textarea>
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="CategoryId">Category</label>
        <select asp-for="CategoryId" asp-items="@ViewBag.Categories" class="form-control"></select>
    </div>
    <div class="form-group">
        <label asp-for="ImageUrl">Product Image</label>
        <input type="file" asp-for="ImageUrl" class="form-control" id="imageInput" /> <br />
        <img id="previewImage" style="max-width: 200px; display: none;" alt="Image preview" />
    </div>
    <br />
    <button type="submit" class="btn btn-primary mt-3 px-3">Update</button>
</form>


<script>
    document.getElementById('imageInput').addEventListener('change', function (event) {
        var output = document.getElementById('previewImage');
        if (this.files && this.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                output.src = e.target.result;
                output.style.display = 'block'; // Show the image
            };
            reader.readAsDataURL(this.files[0]);
        }
    });
</script>